transform_tolerance: 0.1 # Time with which to post-date the transform that is published, to indicate that this transform is valid into the future
min_particles: 50 # Allowed number of particles
max_particles: 500
update_min_d: 0.1 # Translational movement required before performing a filter update
update_min_a: 0.26 # rotational movement required before performing a filter update
resample_interval: 1 # Number of filter updates required before resampling (default 2)

initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.0
initial_cov_yy: 0.0
initial_cov_aa: 0.0

# Laser parameters
laser_min_range: -1 # Scan range to be considered; -1.0 will cause the laser's reported minimum range to be used
laser_max_range: -1
laser_max_beams: 50 # How many evenly-spaced beams in each scan to be used when updating the filter (default 30)
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2 # Standard deviation for Gaussian model used in z_hit part of the model
laser_lambda_short: 0.1 # Exponential decay parameter for z_short part of model

# Odometry model parameters
odom_model_type: diff-corrected # Which model to use, either "diff", "omni", "diff-corrected" or "omni-corrected"
# Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion. -->
odom_alpha1: 0.05 # expected noise in odometry's rotation estimate from the rotational component (default 0.2)
odom_alpha2: 0.05 # expected noise in odometry's rotation estimate from the translational component (default 0.2)
odom_alpha3: 0.05 # expected noise in odometry's translation estimate from the translational component (default 0.2)
odom_alpha4: 0.05 # expected noise in odometry's translation estimate from the rotational component (default 0.2)
odom_alpha5: 0.2 # Translation-related noise parameter (only used if model is "omni")

odom_frame_id: odom # Which frame to use for odometry
base_frame_id: robot_footprint # Which frame to use for the robot base
global_frame_id: map # The name of the coordinate frame published by the localization system
tf_broadcast: true # Set this to false to prevent amcl from publishing the transform between the global frame and the odometry frame
