global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   
   static_map: true # se inicializará con un mapa estático provisto por el map_server
   rolling_window: false
